networks:
  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  back-end:
    image: shl622/stoopit-backend:0.1
    ports:
      - "8080:8080"
  front-end: 
    image: shl622/stoopit-frontend:0.1
    ports:
      - "3000:3000"
